export const countries = {
  AD: 'Andorra',
  AE: 'United Arab Emirates',
  AF: 'Afghanistan',
  AG: 'Antigua and Barbuda',
  AI: 'Anguilla',
  AL: 'Albania',
  AM: 'Armenia',
  AO: 'Angola',
  AQ: 'Antarctica',
  AR: 'Argentina',
  AS: 'American Samoa',
  AT: 'Austria',
  AU: 'Australia',
  AW: 'Aruba',
  AX: 'Åland Islands',
  AZ: 'Azerbaijan',
  BA: 'Bosnia and Herzegovina',
  BB: 'Barbados',
  BD: 'Bangladesh',
  BE: 'Belgium',
  BF: 'Burkina Faso',
  BG: 'Bulgaria',
  BH: 'Bahrain',
  BI: 'Burundi',
  BJ: 'Benin',
  BL: 'Saint Barthélemy',
  BM: 'Bermuda',
  BN: 'Brunei',
  BO: 'Bolivia',
  BQ: 'Caribbean Netherlands',
  BR: 'Brazil',
  BS: 'Bahamas',
  BT: 'Bhutan',
  BW: 'Botswana',
  BY: 'Belarus',
  BZ: 'Belize',
  CA: 'Canada',
  CC: 'Cocos Islands',
  CD: 'Democratic Republic of the Congo',
  CF: 'Central African Republic',
  CG: 'Republic of the Congo',
  CH: 'Switzerland',
  CI: 'Ivory Coast',
  CK: 'Cook Islands',
  CL: 'Chile',
  CM: 'Cameroon',
  CN: 'China',
  CO: 'Colombia',
  CR: 'Costa Rica',
  CU: 'Cuba',
  CV: 'Cabo Verde',
  CW: 'Curaçao',
  CX: 'Christmas Island',
  CY: 'Cyprus',
  CZ: 'Czechia',
  DE: 'Germany',
  DJ: 'Djibouti',
  DK: 'Denmark',
  DM: 'Dominica',
  DO: 'Dominican Republic',
  DZ: 'Algeria',
  EC: 'Ecuador',
  EE: 'Estonia',
  EG: 'Egypt',
  EH: 'Western Sahara',
  ER: 'Eritrea',
  ES: 'Spain',
  ET: 'Ethiopia',
  FI: 'Finland',
  FJ: 'Fiji',
  FK: 'Falkland Islands',
  FM: 'Micronesia',
  FO: 'Faroe Islands',
  FR: 'France',
  GA: 'Gabon',
  GB: 'United Kingdom',
  GD: 'Grenada',
  GE: 'Georgia',
  GF: 'French Guiana',
  GG: 'Guernsey',
  GH: 'Ghana',
  GI: 'Gibraltar',
  GL: 'Greenland',
  GM: 'Gambia',
  GN: 'Guinea',
  GP: 'Guadeloupe',
  GQ: 'Equatorial Guinea',
  GR: 'Greece',
  GS: 'South Georgia and the South Sandwich Islands',
  GT: 'Guatemala',
  GU: 'Guam',
  GW: 'Guinea-Bissau',
  GY: 'Guyana',
  HK: 'Hong Kong',
  HN: 'Honduras',
  HR: 'Croatia',
  HT: 'Haiti',
  HU: 'Hungary',
  ID: 'Indonesia',
  IE: 'Ireland',
  IL: 'Israel',
  IM: 'Isle of Man',
  IN: 'India',
  IO: 'British Indian Ocean Territory',
  IQ: 'Iraq',
  IR: 'Iran',
  IS: 'Iceland',
  IT: 'Italy',
  JE: 'Jersey',
  JM: 'Jamaica',
  JO: 'Jordan',
  JP: 'Japan',
  KE: 'Kenya',
  KG: 'Kyrgyzstan',
  KH: 'Cambodia',
  KI: 'Kiribati',
  KM: 'Comoros',
  KN: 'Saint Kitts and Nevis',
  KP: 'North Korea',
  KR: 'South Korea',
  KW: 'Kuwait',
  KY: 'Cayman Islands',
  KZ: 'Kazakhstan',
  LA: 'Laos',
  LB: 'Lebanon',
  LC: 'Saint Lucia',
  LI: 'Liechtenstein',
  LK: 'Sri Lanka',
  LR: 'Liberia',
  LS: 'Lesotho',
  LT: 'Lithuania',
  LU: 'Luxembourg',
  LV: 'Latvia',
  LY: 'Libya',
  MA: 'Morocco',
  MC: 'Monaco',
  MD: 'Moldova',
  ME: 'Montenegro',
  MF: 'Saint Martin',
  MG: 'Madagascar',
  MH: 'Marshall Islands',
  MK: 'North Macedonia',
  ML: 'Mali',
  MM: 'Myanmar',
  MN: 'Mongolia',
  MO: 'Macao',
  MP: 'Northern Mariana Islands',
  MQ: 'Martinique',
  MR: 'Mauritania',
  MS: 'Montserrat',
  MT: 'Malta',
  MU: 'Mauritius',
  MV: 'Maldives',
  MW: 'Malawi',
  MX: 'Mexico',
  MY: 'Malaysia',
  MZ: 'Mozambique',
  NA: 'Namibia',
  NC: 'New Caledonia',
  NE: 'Niger',
  NF: 'Norfolk Island',
  NG: 'Nigeria',
  NI: 'Nicaragua',
  NL: 'Netherlands',
  NO: 'Norway',
  NP: 'Nepal',
  NR: 'Nauru',
  NU: 'Niue',
  NZ: 'New Zealand',
  OM: 'Oman',
  PA: 'Panama',
  PE: 'Peru',
  PF: 'French Polynesia',
  PG: 'Papua New Guinea',
  PH: 'Philippines',
  PK: 'Pakistan',
  PL: 'Poland',
  PM: 'Saint Pierre and Miquelon',
  PN: 'Pitcairn',
  PR: 'Puerto Rico',
  PS: 'Palestine',
  PT: 'Portugal',
  PW: 'Palau',
  PY: 'Paraguay',
  QA: 'Qatar',
  RE: 'Réunion',
  RO: 'Romania',
  RS: 'Serbia',
  RU: 'Russia',
  RW: 'Rwanda',
  SA: 'Saudi Arabia',
  SB: 'Solomon Islands',
  SC: 'Seychelles',
  SD: 'Sudan',
  SE: 'Sweden',
  SG: 'Singapore',
  SH: 'Saint Helena, Ascension and Tristan da Cunha',
  SI: 'Slovenia',
  SJ: 'Svalbard and Jan Mayen',
  SK: 'Slovakia',
  SL: 'Sierra Leone',
  SM: 'San Marino',
  SN: 'Senegal',
  SO: 'Somalia',
  SR: 'Suriname',
  SS: 'South Sudan',
  ST: 'Sao Tome and Principe',
  SV: 'El Salvador',
  SX: 'Sint Maarten',
  SY: 'Syria',
  SZ: 'Eswatini',
  TC: 'Turks and Caicos Islands',
  TD: 'Chad',
  TF: 'French Southern Territories',
  TG: 'Togo',
  TH: 'Thailand',
  TJ: 'Tajikistan',
  TK: 'Tokelau',
  TL: 'Timor-Leste',
  TM: 'Turkmenistan',
  TN: 'Tunisia',
  TO: 'Tonga',
  TR: 'Türkiye',
  TT: 'Trinidad and Tobago',
  TV: 'Tuvalu',
  TW: 'Taiwan',
  TZ: 'Tanzania',
  UA: 'Ukraine',
  UG: 'Uganda',
  UM: 'United States Minor Outlying Islands',
  US: 'United States of America',
  UY: 'Uruguay',
  UZ: 'Uzbekistan',
  VA: 'Holy See',
  VC: 'Saint Vincent and the Grenadines',
  VE: 'Venezuela',
  VG: 'Virgin Islands (UK)',
  VI: 'Virgin Islands (US)',
  VN: 'Vietnam',
  VU: 'Vanuatu',
  WF: 'Wallis and Futuna',
  WS: 'Samoa',
  YE: 'Yemen',
  YT: 'Mayotte',
  ZA: 'South Africa',
  ZM: 'Zambia',
  ZW: 'Zimbabwe',
}

export const timezones = {
  'Europe/Andorra': 'AD',
  'Asia/Dubai': 'AE',
  'Asia/Kabul': 'AF',
  'America/Antigua': 'AG',
  'America/Anguilla': 'AI',
  'Europe/Tirane': 'AL',
  'Asia/Yerevan': 'AM',
  'America/Curacao': 'AN',
  'Africa/Luanda': 'AO',
  'Antarctica/McMurdo': 'AQ',
  'Antarctica/South_Pole': 'AQ',
  'Antarctica/Palmer': 'AQ',
  'Antarctica/Mawson': 'AQ',
  'Antarctica/Davis': 'AQ',
  'Antarctica/Casey': 'AQ',
  'Antarctica/DumontDUrville': 'AQ',
  'America/Buenos_Aires': 'AR',
  'America/Rosario': 'AR',
  'America/Cordoba': 'AR',
  'America/Jujuy': 'AR',
  'America/Catamarca': 'AR',
  'America/Mendoza': 'AR',
  'Pacific/Pago_Pago': 'AS',
  'Europe/Vienna': 'AT',
  'Australia/Lord_Howe': 'AU',
  'Australia/Hobart': 'AU',
  'Australia/Melbourne': 'AU',
  'Australia/Sydney': 'AU',
  'Australia/Broken_Hill': 'AU',
  'Australia/Brisbane': 'AU',
  'Australia/Lindeman': 'AU',
  'Australia/Adelaide': 'AU',
  'Australia/Darwin': 'AU',
  'Australia/Perth': 'AU',
  'America/Aruba': 'AW',
  'Asia/Baku': 'AZ',
  'Europe/Sarajevo': 'BA',
  'America/Barbados': 'BB',
  'Asia/Dacca': 'BD',
  'Europe/Brussels': 'BE',
  'Africa/Ouagadougou': 'BF',
  'Europe/Sofia': 'BG',
  'Asia/Bahrain': 'BH',
  'Africa/Bujumbura': 'BI',
  'Africa/Porto-Novo': 'BJ',
  'Atlantic/Bermuda': 'BM',
  'Asia/Brunei': 'BN',
  'America/La_Paz': 'BO',
  'America/Noronha': 'BR',
  'America/Belem': 'BR',
  'America/Fortaleza': 'BR',
  'America/Araguaina': 'BR',
  'America/Maceio': 'BR',
  'America/Sao_Paulo': 'BR',
  'America/Cuiaba': 'BR',
  'America/Porto_Velho': 'BR',
  'America/Manaus': 'BR',
  'America/Porto_Acre': 'BR',
  'America/Nassau': 'BS',
  'Asia/Thimbu': 'BT',
  'Africa/Gaborone': 'BW',
  'Europe/Minsk': 'BY',
  'America/Belize': 'BZ',
  'America/St_Johns': 'CA',
  'America/Halifax': 'CA',
  'America/Glace_Bay': 'CA',
  'America/Goose_Bay': 'CA',
  'America/Pangnirtung': 'CA',
  'America/Montreal': 'CA',
  'America/Nipigon': 'CA',
  'America/Thunder_Bay': 'CA',
  'America/Iqaluit': 'CA',
  'America/Winnipeg': 'CA',
  'America/Rainy_River': 'CA',
  'America/Rankin_Inlet': 'CA',
  'America/Regina': 'CA',
  'America/Swift_Current': 'CA',
  'America/Edmonton': 'CA',
  'America/Yellowknife': 'CA',
  'America/Inuvik': 'CA',
  'America/Dawson_Creek': 'CA',
  'America/Vancouver': 'CA',
  'America/Whitehorse': 'CA',
  'America/Dawson': 'CA',
  'Indian/Cocos': 'CC',
  'Africa/Kinshasa': 'CD',
  'Africa/Lubumbashi': 'CD',
  'Africa/Bangui': 'CF',
  'Africa/Brazzaville': 'CG',
  'Europe/Zurich': 'CH',
  'Africa/Abidjan': 'CI',
  'Pacific/Rarotonga': 'CK',
  'America/Santiago': 'CL',
  'Pacific/Easter': 'CL',
  'Africa/Douala': 'CM',
  'Asia/Harbin': 'CN',
  'Asia/Shanghai': 'CN',
  'Asia/Hong_Kong': 'CN',
  'Asia/Chungking': 'CN',
  'Asia/Urumqi': 'CN',
  'Asia/Kashgar': 'CN',
  'America/Bogota': 'CO',
  'America/Costa_Rica': 'CR',
  'America/Havana': 'CU',
  'Atlantic/Cape_Verde': 'CV',
  'Indian/Christmas': 'CX',
  'Asia/Nicosia': 'CY',
  'Europe/Prague': 'CZ',
  'Europe/Berlin': 'DE',
  'Africa/Djibouti': 'DJ',
  'Europe/Copenhagen': 'DK',
  'America/Dominica': 'DM',
  'America/Santo_Domingo': 'DO',
  'Africa/Algiers': 'DZ',
  'America/Guayaquil': 'EC',
  'Pacific/Galapagos': 'EC',
  'Europe/Tallinn': 'EE',
  'Africa/Cairo': 'EG',
  'Africa/El_Aaiun': 'EH',
  'Africa/Asmera': 'ER',
  'Europe/Madrid': 'ES',
  'Africa/Ceuta': 'ES',
  'Atlantic/Canary': 'ES',
  'Africa/Addis_Ababa': 'ET',
  'Europe/Helsinki': 'FI',
  'Pacific/Fiji': 'FJ',
  'Atlantic/Stanley': 'FK',
  'Pacific/Yap': 'FM',
  'Pacific/Truk': 'FM',
  'Pacific/Ponape': 'FM',
  'Pacific/Kosrae': 'FM',
  'Atlantic/Faeroe': 'FO',
  'Europe/Paris': 'FR',
  'Africa/Libreville': 'GA',
  'Europe/London': 'GB',
  'Europe/Belfast': 'GB',
  'America/Grenada': 'GD',
  'Asia/Tbilisi': 'GE',
  'America/Cayenne': 'GF',
  'Africa/Accra': 'GH',
  'Europe/Gibraltar': 'GI',
  'America/Scoresbysund': 'GL',
  'America/Godthab': 'GL',
  'America/Thule': 'GL',
  'Africa/Banjul': 'GM',
  'Africa/Conakry': 'GN',
  'America/Guadeloupe': 'GP',
  'Africa/Malabo': 'GQ',
  'Europe/Athens': 'GR',
  'Atlantic/South_Georgia': 'GS',
  'America/Guatemala': 'GT',
  'Pacific/Guam': 'GU',
  'Africa/Bissau': 'GW',
  'America/Guyana': 'GY',
  'America/Tegucigalpa': 'HN',
  'Europe/Zagreb': 'HR',
  'America/Port-au-Prince': 'HT',
  'Europe/Budapest': 'HU',
  'Asia/Jakarta': 'ID',
  'Asia/Ujung_Pandang': 'ID',
  'Asia/Jayapura': 'ID',
  'Europe/Dublin': 'IE',
  'Asia/Jerusalem': 'IL',
  'Asia/Calcutta': 'IN',
  'Indian/Chagos': 'IO',
  'Asia/Baghdad': 'IQ',
  'Asia/Tehran': 'IR',
  'Atlantic/Reykjavik': 'IS',
  'Europe/Rome': 'IT',
  'America/Jamaica': 'JM',
  'Asia/Amman': 'JO',
  'Asia/Tokyo': 'JP',
  'Africa/Nairobi': 'KE',
  'Asia/Bishkek': 'KG',
  'Asia/Phnom_Penh': 'KH',
  'Pacific/Tarawa': 'KI',
  'Pacific/Enderbury': 'KI',
  'Pacific/Kiritimati': 'KI',
  'Indian/Comoro': 'KM',
  'America/St_Kitts': 'KN',
  'Asia/Pyongyang': 'KP',
  'Asia/Seoul': 'KR',
  'Asia/Kuwait': 'KW',
  'America/Cayman': 'KY',
  'Asia/Almaty': 'KZ',
  'Asia/Aqtobe': 'KZ',
  'Asia/Aqtau': 'KZ',
  'Asia/Vientiane': 'LA',
  'Asia/Beirut': 'LB',
  'America/St_Lucia': 'LC',
  'Europe/Vaduz': 'LI',
  'Asia/Colombo': 'LK',
  'Africa/Monrovia': 'LR',
  'Africa/Maseru': 'LS',
  'Europe/Vilnius': 'LT',
  'Europe/Luxembourg': 'LU',
  'Europe/Riga': 'LV',
  'Africa/Tripoli': 'LY',
  'Africa/Casablanca': 'MA',
  'Europe/Monaco': 'MC',
  'Europe/Chisinau': 'MD',
  'Indian/Antananarivo': 'MG',
  'Pacific/Majuro': 'MH',
  'Pacific/Kwajalein': 'MH',
  'Europe/Skopje': 'MK',
  'Africa/Bamako': 'ML',
  'Africa/Timbuktu': 'ML',
  'Asia/Rangoon': 'MM',
  'Asia/Ulan_Bator': 'MN',
  'Asia/Macao': 'MO',
  'Pacific/Saipan': 'MP',
  'America/Martinique': 'MQ',
  'Africa/Nouakchott': 'MR',
  'America/Montserrat': 'MS',
  'Europe/Malta': 'MT',
  'Indian/Mauritius': 'MU',
  'Indian/Maldives': 'MV',
  'Africa/Blantyre': 'MW',
  'America/Cancun': 'MX',
  'America/Mexico_City': 'MX',
  'America/Mazatlan': 'MX',
  'America/Chihuahua': 'MX',
  'America/Ensenada': 'MX',
  'America/Tijuana': 'MX',
  'America/Monterrey': 'MX',
  'Asia/Kuala_Lumpur': 'MY',
  'Asia/Kuching': 'MY',
  'Africa/Maputo': 'MZ',
  'Africa/Windhoek': 'NA',
  'Pacific/Noumea': 'NC',
  'Africa/Niamey': 'NE',
  'Pacific/Norfolk': 'NF',
  'Africa/Lagos': 'NG',
  'America/Managua': 'NI',
  'Europe/Amsterdam': 'NL',
  'Europe/Oslo': 'NO',
  'Asia/Katmandu': 'NP',
  'Pacific/Nauru': 'NR',
  'Pacific/Niue': 'NU',
  'Pacific/Auckland': 'NZ',
  'Pacific/Chatham': 'NZ',
  'Asia/Muscat': 'OM',
  'America/Panama': 'PA',
  'America/Lima': 'PE',
  'Pacific/Tahiti': 'PF',
  'Pacific/Marquesas': 'PF',
  'Pacific/Gambier': 'PF',
  'Pacific/Port_Moresby': 'PG',
  'Asia/Manila': 'PH',
  'Asia/Karachi': 'PK',
  'Europe/Warsaw': 'PL',
  'America/Miquelon': 'PM',
  'Pacific/Pitcairn': 'PN',
  'America/Puerto_Rico': 'PR',
  'Asia/Gaza': 'PS',
  'Europe/Lisbon': 'PT',
  'Atlantic/Madeira': 'PT',
  'Atlantic/Azores': 'PT',
  'Pacific/Palau': 'PW',
  'America/Asuncion': 'PY',
  'Asia/Qatar': 'QA',
  'Indian/Reunion': 'RE',
  'Europe/Bucharest': 'RO',
  'Europe/Kaliningrad': 'RU',
  'Europe/Moscow': 'RU',
  'Europe/Samara': 'RU',
  'Asia/Yekaterinburg': 'RU',
  'Asia/Omsk': 'RU',
  'Asia/Novosibirsk': 'RU',
  'Asia/Krasnoyarsk': 'RU',
  'Asia/Irkutsk': 'RU',
  'Asia/Yakutsk': 'RU',
  'Asia/Vladivostok': 'RU',
  'Asia/Magadan': 'RU',
  'Asia/Kamchatka': 'RU',
  'Asia/Anadyr': 'RU',
  'Africa/Kigali': 'RW',
  'Asia/Riyadh': 'SA',
  'Pacific/Guadalcanal': 'SB',
  'Indian/Mahe': 'SC',
  'Africa/Khartoum': 'SD',
  'Europe/Stockholm': 'SE',
  'Asia/Singapore': 'SG',
  'Atlantic/St_Helena': 'SH',
  'Europe/Ljubljana': 'SI',
  'Arctic/Longyearbyen': 'SJ',
  'Atlantic/Jan_Mayen': 'SJ',
  'Europe/Bratislava': 'SK',
  'Africa/Freetown': 'SL',
  'Europe/San_Marino': 'SM',
  'Africa/Dakar': 'SN',
  'Africa/Mogadishu': 'SO',
  'America/Paramaribo': 'SR',
  'Africa/Sao_Tome': 'ST',
  'America/El_Salvador': 'SV',
  'Asia/Damascus': 'SY',
  'Africa/Mbabane': 'SZ',
  'America/Grand_Turk': 'TC',
  'Africa/Ndjamena': 'TD',
  'Indian/Kerguelen': 'TF',
  'Africa/Lome': 'TG',
  'Asia/Bangkok': 'TH',
  'Asia/Dushanbe': 'TJ',
  'Pacific/Fakaofo': 'TK',
  'Asia/Ashkhabad': 'TM',
  'Africa/Tunis': 'TN',
  'Pacific/Tongatapu': 'TO',
  'Europe/Istanbul': 'TR',
  'America/Port_of_Spain': 'TT',
  'Pacific/Funafuti': 'TV',
  'Asia/Taipei': 'TW',
  'Africa/Dar_es_Salaam': 'TZ',
  'Europe/Kiev': 'UA',
  'Europe/Simferopol': 'UA',
  'Africa/Kampala': 'UG',
  'Pacific/Johnston': 'UM',
  'Pacific/Midway': 'UM',
  'Pacific/Wake': 'UM',
  'America/New_York': 'US',
  'America/Detroit': 'US',
  'America/Louisville': 'US',
  'America/Indianapolis': 'US',
  'America/Indiana/Marengo': 'US',
  'America/Indiana/Knox': 'US',
  'America/Indiana/Vevay': 'US',
  'America/Chicago': 'US',
  'America/Menominee': 'US',
  'America/Denver': 'US',
  'America/Boise': 'US',
  'America/Shiprock': 'US',
  'America/Phoenix': 'US',
  'America/Los_Angeles': 'US',
  'America/Anchorage': 'US',
  'America/Juneau': 'US',
  'America/Yakutat': 'US',
  'America/Nome': 'US',
  'America/Adak': 'US',
  'Pacific/Honolulu': 'US',
  'America/Montevideo': 'UY',
  'Asia/Samarkand': 'UZ',
  'Asia/Tashkent': 'UZ',
  'Europe/Vatican': 'VA',
  'America/St_Vincent': 'VC',
  'America/Caracas': 'VE',
  'America/Tortola': 'VG',
  'America/St_Thomas': 'VI',
  'Asia/Saigon': 'VN',
  'Pacific/Efate': 'VU',
  'Pacific/Wallis': 'WF',
  'Pacific/Apia': 'WS',
  'Asia/Aden': 'YE',
  'Indian/Mayotte': 'YT',
  'Europe/Belgrade': 'YU',
  'Africa/Johannesburg': 'ZA',
  'Africa/Lusaka': 'ZM',
  'Africa/Harare': 'ZW',
}

export function getCountry(timezone) {
  return countries[timezones[timezone]]
}
